name: Run multi-jobs workflow sequentially

on:
  repository_dispatch:
    types:
      - fire
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose ENV"
        required: true
        default: dev
        type: choice
        options: [dev, prod]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: echo Job ${{github.job}}

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo Job ${{github.job}}

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - run: echo Job ${{github.job}}

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - run: echo Job ${{github.job}}
