name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  exp1:
    runs-on: ubuntu-latest

    steps:
      - name: log welcome msg
        run: echo "hi from ubuntu linux, this is gh workflow"

      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: List all files
        run: ls -la
