name: Manual Workflow

on:
  repository_dispatch:
    types:
      - incident_report

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delpoy manual
        run: echo "Deployment workflow manually with API Call"
